spring:
  datasource:
    url: jdbc:mariadb://192.168.75.198:3306/rundrydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: rundry_user
    password: wpfkem12

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true